### ISSUE TITLE
Attribute absolute="1" of viewhelper does not work correctly for config.absRefPrefix = auto

### ISSUE THREAD

**Issue by mediaessenz** [helhum/typoscript_rendering#39]
To reproduce use this setting in TypoScript setup:
`config.absRefPrefix = auto`

then add an viewhelper to generate an ajax action link into a fluid template:
`<tsr:uri.ajaxAction controller="ControllerName" action="actionName" absolute="1" />`

Call site using **https**

The result will be an **http**-URL and **not** an https

A possible solution to solve this problem would be to add an additional attribute "absoluteUriScheme" to the ajaxAction viewhelper, and hands over the value (if defined) to the uri builder.

This problem exists under TYPO3 7.6.21, but maybe also under 8.7.x.

If my suggestion is acceptable, I would create a pull request.

**Comment by helhum** [comment]
`AjaxActionViewHelper` calls `\TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder` and just passes the `absolute` flag to it. This means, if there is a bug, it is located in TYPO3, not typoscript_rendering.

Since `UriBuilder` passes this option to `typolink()`, the bug would be in `typolink()`

Could it be, that your TYPO3 is behind a (SSL terminating) proxy and you did not configure TYPO3 to detect this proxy?

**Comment by mediaessenz** [comment]
You are right, the problem comes from my local development environment, which is using a proxy.
