### ISSUE TITLE
Ajax links rendered after a call to typoscript_rendering gets wrong currentRecord

### ISSUE THREAD

**Issue by numito** [helhum/typoscript_rendering#7]
when calling an ajax link created with typoscript_rendering that renders content containing ajax links created with typescript_rendering then the currentContent is a page instead of tt_content.
ex: ajax paging
1/ first load shows page containing a plugin that generates ajax links, ajax links will have a context of tt_content_xxx (the plugin context)
2/ clicking on the ajax links renders new content from this same plugin, output contains new ajax links
3/ these new ajax links are wrong because they have a context of page_xxx instead of tt_content_xxx 

Is there a way that a plugin rendering ajax links that will recursively call the same plugin with different parameters keeps the correct context (tt_content) from the initial page call.

**Comment by numito** [comment]
Hello,
Just noticed that I forgot the basic rules of politeness, was too much into figuring out what was wrong. 
So thanks for the plugin and thanks for your help.
Numa

**Comment by numito** [comment]
Hello,

I found out the issue, I was initializing a StandaloneView without pass the current content object in parameter, therefor it recreated an empty content object for the view.

it was 
```php
$this->objectManager->get('TYPO3\\CMS\\Fluid\\View\\StandaloneView');
```
but it should be 
```php
$this->objectManager->get('TYPO3\\CMS\\Fluid\\View\\StandaloneView', $this->configurationManager->getContentObject());
```

**Comment by Kitzberger** [comment]
Hi,

I'm experiencing a similar issue under TYPO3 7.6.6 but not with recursive rendering as described above. With TYPO3 6.2 it worked as expected. The AJAX url points to the page record instead of the tt_content record, so the plugin is rendered but without knowing anything about the flexform settings.

When debugging AjaxActionViewHelper the current record ($this->configurationManager->getContentObject()->currentRecord) is just empty.

Is this a already known issue with TYPO3 7? Any help is apprechiated.

Philipp

**Comment by helhum** [comment]
Hi @Kitzberger! Assuming you use fluid_styled_content rendering, you should wait for the new bugfix version of TYPO3 or apply this simple bugfix to your project: https://review.typo3.org/#/c/48011/

Please let me know if my advice helped

**Comment by Kitzberger** [comment]
Thank you @helhum, that did the trick ;-)
