### ISSUE TITLE
Ajax response always contains complete page html

### ISSUE THREAD

**Issue by fishbone1** [helhum/typoscript_rendering#89]
I found lots of articles that suggest to use your extension for ajax requests.

My actual use case is to mark a news as being read via an ajax call. I'm using the extension mediadreams/md_unreadnews which contains a controller action for that. They have a view helper that calls the controller action which is meant to be included on the news detail page. I need ajax, because I have no detail page. Instead all news are loaded before and an entry is displayed with javascript.

I generated following URLs in my page template:

```
<script>
   [
       '<t:uri.ajaxAction pluginName="Unread" controller="Unreadnews" action="removeUnread" />',
       '<t:uri.ajaxAction extensionName="MdUnreadnews" pluginName="Unread" controller="Unreadnews" action="removeUnread" />',
       '<t:uri.ajaxAction extensionName="Mediadreams.MdUnreadnews" pluginName="Unread" controller="Unreadnews" action="removeUnread" />',
  ].forEach(url => {
       $.post(url).then(resp => console.log(url, resp));
  })
</script>
```

I removed the first one, because it will produce an error:

> Argument 1 passed to Helhum\TyposcriptRendering\Uri\TyposcriptRenderingUri::buildTypoScriptRenderingConfiguration() must be of the type string, null given

The required arguments `pluginName` and `controller` make sense for me. However it confuses me that most of the resources found on the web don't pass those arguments.

Requests to URLs 2 and 3 respond with a complete page HTML, although I temporarily edited the controller action to throw an error on the first line. I also set a debug breakpoint at the first line and therefore can see that the action is not called.

Next, I registered a plugin and implemented a controller in my own site package extension and tried to call that with ajax. The result is the same.

ext_localconf.php
```
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
    'my_site_package',
    'Unread',
    [
        \MySitePackage\Controller\UnreadnewsController::class => 'removeUnread'
    ],
    // non-cacheable actions
    [
        \MySitePackage\Controller\UnreadnewsController::class => 'removeUnread'
    ]
);
```

.../my_site_package/Resources/Private/Templates/Page/Default.html
```
<t:uri.ajaxAction extensionName="my_site_package" pluginName="Unread" controller="Unreadnews" action="removeUnread" />
<t:uri.ajaxAction extensionName="MySitePackage" pluginName="Unread" controller="Unreadnews" action="removeUnread" />
```

Typo3 11.5.9
helhum/typoscript-rendering 2.4

**Comment by helhum** [comment]
A few hints here:

## 1. The uri and link view helper in TypoScript Rendering work exactly the same as Extbase's according view helpers

In fact you should use them like so `<t:uri.action ... />`, the old names `<t:uri.ajaxAction ... />` are deprecated and only work for backwards compatibility.

I suggest you catch up with understanding why and when you need to specify `pluginName` and `extensionName` for these view helpers Extbase ships. The same rules apply for the view helpers this extension ships

The only difference is, that the TypoScript Rendering view helpers adds an additional argument to the URI `&tx_typoscriptrendering[context]=...` With this argument being in the URL, TypoScript Rendering will only return the response of the specified plugin, not the whole HTML document.

## 2. Verify, whether you put the correct namespace import into your Template:

```html
<html
    xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
    xmlns:t="http://typo3.org/ns/Helhum/TyposcriptRendering/ViewHelpers"
    data-namespace-typo3-fluid="true">
...
```

## 3. Put the resulting URI from the view helper in the browser and verify whether you get the response from the plugin, as you expect.

Last but not least: Creating an issue here is fine. You also provided some code snippets, which is good as well. In addition you should add a more complete context to the snippets, like the full HTML, so that for another person it is possible to recreate the exact issue you are seeing. A complete example repo with all code would be perfect. Otherwise it is impossible to know what is going wrong for you and thus not possible to really help any further.

I double checked with helhum/typoscript-rendering 2.4.1 in a new project with TYPO3 11.5.22 and everything works in my test cases like expected.

Therefore I'll close this issue here. Feel free to come up with more information (like a complete example to reproduce) and add it here. I will see and answer as time allows

**Comment by fishbone1** [comment]
Thanks for your response. I didn't give you all the code as I don't know where it is caused. So I'd have to priovide the whole code. Maybe I can make a minimalistic extension. I hoped that it will be clear where the problem is or if it's a known problem...

The namespace is correct. Otherwise I wouldn't get the error from your extension.

I have an essential question:

Can the ajax URL only be generated in a plugin itself? I'm generating it from a normal template (outside of a plugin) or from the page layout. I saw your ajax_exmaple where it seems to be generated in a plugin.

**Comment by helhum** [comment]
> Can the ajax URL only be generated in a plugin itself? 

Let me cite from my response above: 
> The uri and link view helper in TypoScript Rendering work exactly the same as Extbase's according view helpers

It could work somehow, but it would be more robust to generate all links to a plugin from within this plugin's template.

**Comment by fishbone1** [comment]
I turns out that it works if I put the plugin (e.g. 'Unread' in my case) on the page where the URL is generated. Maybe this is how it is meant to be in your extension (?) but it's not what I wanted to do. I wanted to call the Extbase action without having the plugin on the page. I thought this is why others use a custom page type.

It also turned out that extension MdUnreadnews can already do that (so I wasted lots of time). And they're also using a custom page type. I'm really suprised, how simple it is:

```
# setup.typoscript
/**
 * used for ajax call to remove unread information
 *
 */
PAGE_REMOVE_UNREAD_NEWS = PAGE
PAGE_REMOVE_UNREAD_NEWS {
    typeNum = 120719

    config {
        disableAllHeaderCode = 1
        additionalHeaders = Content-type:application/html
        xhtml_cleaning = 0
        debug = 0
        admPanel = 0
    }

    10 = USER_INT
    10 {
        userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
        extensionName = MdUnreadnews
        pluginName = Unread
        vendorName = Mediadreams

        switchableControllerActions {
            Unreadnews {
                1 = removeUnread
            }
        }

        settings {
            useStdWrap := addToList(newsUid)

            newsUid = TEXT
            newsUid.data = GP:newsUid
        }
    }
}
```

So I can send my ajax request to `/index.php?type=120719&newsUid=...`

This indeed works everywhere. No need to put a plugin anywhere.

Disadvantage is the page typeNum. I found your extension, because I wanted to get rid of that.
